### ISSUE TITLE
chaotic spi in audioplayer

### ISSUE THREAD

**Issue by LovelyA72** [free-pdk/easy-pdk-showcase-projects#1]
Hello, I am currently trying to make audioplayer work on a PFS154.
However, the example does not work at all. After probing on the SPI line I found that not only the timing is a mess, the padauk is driving the MISO pin which it needs to be listening to instead of driving.

**Comment by freepdk** [comment]
SDCC changed assembler syntax for operations with IO. 

Look here for details: https://www.eevblog.com/forum/blog/eevblog-1144-padauk-programmer-reverse-engineering/msg3955892/#msg3955892

All projects been updated with commit 0a82dfbfca3656f6f5e5c17c818249734a20f67c .
They now require a recent SDCC (>=4.1.10) to be compiled.
